### ISSUE TITLE
Deploy service to AWS EC2 instance

### ISSUE THREAD

**Issue by alindenberg** [UltimateSoftware/fg-server#50]
* **Summary**
We need to deploy this service to a public EC2 instance so that the frontend may use it when its live.

**Comment by alindenberg** [comment]
Currently done with branch feature/deploy-service, waiting to obtain AWS account from the FG team and we will deploy on there.

**Comment by markd315** [comment]
Hey, I was hoping for an update on this, we have it right?

**Comment by markd315** [comment]
http://ec2-34-201-168-0.compute-1.amazonaws.com:5000/api-docs/
