### ISSUE TITLE
Add attendee property to Hangouts

### ISSUE THREAD

**Issue by juansuh** [UltimateSoftware/fg-server#58]
* **I'm submitting a ...**
[ X] feature request

* **Summary**
Hangouts currently do not track which members are attending it, so since the frontend has added the ability to RSVP we should implement that. 

* **Other information** 
This will involve a POST command to add an attendee, a GET command to see if a member is on the list, and a DELETE command to remove an attendee. Attendees will be stored based on their unique ID.

**Comment by markd315** [comment]
Okay, I can take this I think. Might have some time today even after lunch to start.

**Comment by markd315** [comment]
PR

**Comment by markd315** [comment]
PR, closing issue https://github.com/UltimateSoftware/fg-server/pull/59
