### ISSUE TITLE
Add endpoint to get events by chapterId

### ISSUE THREAD

**Issue by cheffley6** [UltimateSoftware/fg-server#74]

**Comment by markd315** [comment]
taking today, sorry I forgot about it

**Comment by markd315** [comment]
Not a new endpoint, implemented as a query parameter in the existing GET, 

PR: https://github.com/UltimateSoftware/fg-server/pull/77

sample cURL:
curl -X GET \
  'http://ec2-34-201-168-0.compute-1.amazonaws.com:5000/events?chapterId=99999999-cccc-4a96-b827-fa80954d9cff' \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJUazROVE15UVRZMU5EbENNVGN4TURJNE1qQXhSa1pETmtReU1FSTFPRFJHUmpWQk1qRTVNUSJ9.eyJpc3MiOiJodHRwczovL2ZlYXJsZXNzbHlnaXJsLmF1dGgwLmNvbS8iLCJzdWIiOiJxeXdScjFYYTVxYkFrclhLNVhKazZjRko2dkdDZUl0ekBjbGllbnRzIiwiYXVkIjoib2F1dGgvdG9rZW4iLCJpYXQiOjE1NjM5MTAwODYsImV4cCI6MTU2Mzk5NjQ4NiwiYXpwIjoicXl3UnIxWGE1cWJBa3JYSzVYSms2Y0ZKNnZHQ2VJdHoiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.PmiDx1mbOt-H9XTvfgOgg0O7b_MgF1v30TRjFB9hAC1maedNjHKTz3RpgupVXR26RkLxSgc1aqxKRFYAp36Bce5IyVldIahJ0Q8CROjCu3OFoo7Z__bzICIngbSFlRFsSLv5KAcassA0r8owR8ISjEun8zJMChmPi7KVBGaukbekXjwCLOkYYavR2x_UwZCs0ZYzIa1roxeCf8enWqYLkJVqNiSqa0ufqVC-4MxOUyErAgO_mvLkbAgLO-4UVJkY1Mt5QdusLiblczhw-cToO8TGVwN5dT-pYxR1iJNk1Jymj5kzH27pc0xafCEET_iYFnF4NfeKX-p3k9CGL7uPNw' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:5000'
