### ISSUE TITLE
Return ID with templates

### ISSUE THREAD

**Issue by audgster** [UltimateSoftware/fg-server#75]
* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Return ID with templates. When getting the template list, we only get back an array of names. Need to also get IDs so that we can look up full descriptions.

**Comment by markd315** [comment]
PR: https://github.com/UltimateSoftware/fg-server/pull/77
