### ISSUE TITLE
Support get by ID for hangout templates

### ISSUE THREAD

**Issue by audgster** [UltimateSoftware/fg-server#76]
* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Support get by ID for hangout templates. This will allow for the front end to efficiently retrieve single hangouts.

**Comment by markd315** [comment]
PR: https://github.com/UltimateSoftware/fg-server/pull/77
